# Site Configuration
# Edit this file to update global site settings

site:
  title: "Unmuted"
  tagline: "A hub that flips the script — smart, funny pop culture commentary where every fan feels at home"
  description: "Finally—commentary that's worth your time. We break down Pretty Little Liars, Gossip Girl, Glee, and more with smart analysis, actual humor, and inclusive perspectives."
  url: "https://adrianaso123.github.io/unmuted"
  author: "Unmuted"
  language: "en"
  
  # Contact Information
  phone: ""
  phone_raw: ""
  email: "hello@unmuted.com"
  whatsapp: ""
  
  # Location
  location:
    city: ""
    region: ""
    coordinates:
      latitude: 0
      longitude: 0
  
  # Social Media (set real URLs or leave empty to hide)
  social:
    facebook: ""
    instagram: ""
    linkedin: ""
    twitter: ""
  
  # SEO Keywords
  keywords:
    - "2010s teen dramas"
    - "diverse pop culture opinions"
    - "minority perspectives TV"
    - "Gossip Girl analysis"
    - "Pretty Little Liars review"
    - "Teen Wolf commentary"
    - "The Vampire Diaries"
    - "Glee diversity"
    - "teen drama representation"
    - "pop culture criticism"

# Build Configuration
build:
  output_dir: "docs"
  static_dir: "static"
  template_dir: "templates"
  
# Feature Flags
features:
  show_blog: false
  show_testimonials: true
  show_whatsapp_float: false
  show_pricing: false
  enable_analytics: false
